language: generic
sudo: required
services:
    - docker

before_install:
    - docker build . -t dgasioro/react-test -f ./client/Dockerfile.dev

script:
    - docker run -e CI=true dgasioro/react-test npm run test -- --coverage

after_success:
    - docker build -t dgasioro/multi-client ./client
    - docker build -t dgasioro/multi-nginx ./nginx
    - docker build -t dgasioro/multi-server ./server
    - docker build -t dgasioro/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push dgasioro/multi-client
    - docker push dgasioro/multi-nginx
    - docker push dgasioro/multi-server
    - docker push dgasioro/multi-worker